/**
 * Agent-facing guidance generated by `kazam sdk emit-mcp` (pnpm generate).
 * Tool descriptions, the server-instructions section, and per-component
 * slices all come from the kazam schema, so a component that gains guidance
 * upstream shows up here on the next regenerate with no hand edits.
 */
import bundle from "@/generated/kazam-mcp.json";

interface GuidanceRule {
  warn: string;
  say: string;
  severity: string;
}

interface ComponentSlice {
  use_when: string | null;
  avoid_when: string | null;
  example_name: string | null;
  example_yaml: string | null;
  rules: GuidanceRule[];
}

interface Bundle {
  guided_components: string[];
  tools: Record<string, string>;
  instructions_section: string;
  components: Record<string, ComponentSlice>;
}

const data = bundle as unknown as Bundle;

export function guidedComponents(): string[] {
  return data.guided_components;
}

/** Description for a write/reference tool; falls back to the caller's text. */
export function toolDescription(tool: string, fallback: string): string {
  return data.tools[tool] ?? fallback;
}

export function instructionsSection(): string {
  return data.instructions_section;
}

export function componentSlice(type: string): ComponentSlice | null {
  return data.components[type] ?? null;
}

/** Markdown slice for one component: guidance, curated example, rules. */
export function renderComponentSlice(type: string): string | null {
  const s = componentSlice(type);
  if (!s) return null;
  const out: string[] = [`## ${type}`, ""];
  if (s.use_when) out.push(`**Use when:** ${s.use_when}`);
  if (s.avoid_when) out.push(`**Avoid when:** ${s.avoid_when}`);
  if (s.use_when || s.avoid_when) out.push("");
  if (s.example_yaml) {
    out.push("Copy this structure:", "", "```yaml", s.example_yaml.trimEnd(), "```", "");
  }
  if (s.rules.length > 0) {
    out.push("**Shape rules (warn on write):**");
    for (const r of s.rules) out.push(`- ${r.say} (\`${r.warn}\`)`);
    out.push("");
  }
  return out.join("\n");
}
