export interface Template {
  slug: string;
  title: string;
  description: string;
  group: string;
  previewUrl: string;
}

export const TEMPLATES: Template[] = [
  // Data
  {
    slug: "chart",
    title: "Chart: Bar / Pie / Timeseries",
    description: "Customer health tiers as a bar chart with ARR on the y-axis and semantic color per tier.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-chart",
  },
  {
    slug: "chart-group",
    title: "Chart Group: Side-by-Side",
    description: "Two charts in a single row: a timeseries of daily page volume next to a bar chart of trust rate.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-chart-group",
  },
  {
    slug: "gauge",
    title: "Gauge: Scoring Dashboard",
    description: "One gauge per CIS control domain, filled to the maturity score out of five.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-gauge",
  },
  {
    slug: "sankey",
    title: "Sankey: Flow Diagram",
    description: "A recruiting funnel from sourcing channel to final disposition, sized by candidate count.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-sankey",
  },
  {
    slug: "radar",
    title: "Radar: Multi-Axis Comparison",
    description: "Account health across five axes with two customers overlaid for side-by-side comparison.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-radar",
  },
  {
    slug: "quadrant",
    title: "Quadrant: Effort vs Impact",
    description: "Feature requests plotted on effort vs impact with named quadrant labels for each action zone.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-quadrant",
  },
  {
    slug: "venn",
    title: "Venn: Overlap Analysis",
    description: "Sales, support, and engineering topic coverage with the shared center labeled.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-venn",
  },
  {
    slug: "graph",
    title: "Graph: Concept Map",
    description: "Ten brain pages as nodes with edges labeled by the shared tag linking them.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-graph",
  },
  {
    slug: "progress-bar",
    title: "Progress Bar: Migration Tracker",
    description: "One bar per legacy system being retired, with color thresholds at key milestones.",
    group: "Data",
    previewUrl: "/p/curata-internal/template-progress-bar",
  },
  // Structure
  {
    slug: "org-chart",
    title: "Org Chart",
    description: "A customer org chart with titles, LinkedIn links, and tags flagging the economic buyer.",
    group: "Structure",
    previewUrl: "/p/curata-internal/template-org-chart",
  },
  {
    slug: "role-map",
    title: "Role Map: Who Owns What",
    description: "Incident response and deal desk roles with authority tables showing who signs off.",
    group: "Structure",
    previewUrl: "/p/curata-internal/template-role-map",
  },
  {
    slug: "tree",
    title: "Tree: Hierarchy Browser",
    description: "Folder taxonomy with ownership notes, plus an engineering roadmap with status-colored tasks.",
    group: "Structure",
    previewUrl: "/p/curata-internal/template-tree",
  },
  {
    slug: "architecture-diagram",
    title: "Architecture: System Diagram",
    description: "The AI-native loop as five connected nodes with labeled data flows between each.",
    group: "Structure",
    previewUrl: "/p/curata-internal/template-architecture-diagram",
  },
  {
    slug: "pipeline",
    title: "Pipeline: Stage Flow",
    description: "The capture-to-trusted pipeline with raw pages flowing through human review to validated output.",
    group: "Structure",
    previewUrl: "/p/curata-internal/template-pipeline",
  },
  // Sequence
  {
    slug: "event-timeline",
    title: "Event Timeline: Postmortem",
    description: "An incident timeline from detection to resolution with severity tags and source attribution.",
    group: "Sequence",
    previewUrl: "/p/curata-internal/template-event-timeline",
  },
  {
    slug: "before-after",
    title: "Before / After Comparison",
    description: "The same question answered from tribal memory vs the brain, with source attribution.",
    group: "Sequence",
    previewUrl: "/p/curata-internal/template-before-after",
  },
  {
    slug: "priority-queue",
    title: "Priority Queue: Rollout Plan",
    description: "A phased Curata rollout plan with now/next/later horizons, dates, and status tracking.",
    group: "Sequence",
    previewUrl: "/p/curata-internal/template-priority-queue",
  },
  // Layout
  {
    slug: "columns",
    title: "Columns: Runbook with Asides",
    description: "Deploy steps on the left, reasoning asides on the right explaining why each step matters.",
    group: "Layout",
    previewUrl: "/p/curata-internal/template-columns",
  },
  {
    slug: "split-compare",
    title: "Split Compare: Side by Side",
    description: "Before and after Curata stats compared panel by panel with colored indicators.",
    group: "Layout",
    previewUrl: "/p/curata-internal/template-split-compare",
  },
  {
    slug: "hero-banner",
    title: "Hero Banner: Landing Page",
    description: "A new-hire onboarding hub with a welcome hero, action buttons, and resource cards.",
    group: "Layout",
    previewUrl: "/p/curata-internal/template-hero-banner",
  },
  {
    slug: "image",
    title: "Image: Brand Assets",
    description: "Logo placement with caption, alt text, and alignment options.",
    group: "Layout",
    previewUrl: "/p/curata-internal/template-image",
  },
  {
    slug: "aside",
    title: "Aside: Margin Notes",
    description: "A pricing policy with inline asides explaining the finance reasoning behind each cap.",
    group: "Layout",
    previewUrl: "/p/curata-internal/template-aside",
  },
  {
    slug: "empty-state",
    title: "Empty State: First-Run Page",
    description: "The page a new org sees before its first capture, with a call-to-action to get started.",
    group: "Layout",
    previewUrl: "/p/curata-internal/template-empty-state",
  },
  // Existing non-showcase templates
  {
    slug: "showcase-deck",
    title: "Deck: Slide Presentation",
    description: "A slide-by-slide narrative with a cover slide, built for a live walkthrough like a QBR.",
    group: "Present",
    previewUrl: "/p/curata-internal/template-showcase-deck",
  },
  {
    slug: "showcase-hub",
    title: "Hub: Multi-Page Collection",
    description: "Shared navigation and one status across a small set of related pages, like a launch hub.",
    group: "Present",
    previewUrl: "/p/curata-internal/template-showcase-hub",
  },
  {
    slug: "showcase-shared-component",
    title: "Shared Component",
    description: "A fact written once and embedded everywhere, so one approval updates every page that references it.",
    group: "Reuse",
    previewUrl: "/p/curata-internal/template-showcase-shared-component",
  },
  {
    slug: "showcase-ref-embeds",
    title: "Page With Embedded Components",
    description: "Embeds a shared component page twice, mixed with its own content, using a ref block.",
    group: "Reuse",
    previewUrl: "/p/curata-internal/template-showcase-ref-embeds",
  },
  {
    slug: "showcase-steps-checklist",
    title: "Steps and Checklists",
    description: "Numbered steps for a runbook, plus an unordered list for pre-flight items where order doesn't matter.",
    group: "Procedures",
    previewUrl: "/p/curata-internal/template-showcase-steps-checklist",
  },
  {
    slug: "skill",
    title: "Skill: Agent Procedure",
    description: "An agent procedure: trigger, steps, and an optionally AGL-validated flow",
    group: "Procedures",
    previewUrl: "/p/curata-internal/template-skill",
  },
  {
    slug: "showcase-stat-timeline",
    title: "Stats and Timelines",
    description: "A stat grid for the headline numbers, and a timeline underneath for status at a glance.",
    group: "Structured data",
    previewUrl: "/p/curata-internal/template-showcase-stat-timeline",
  },
  {
    slug: "showcase-tables",
    title: "Tables and Card Grids",
    description: "A filterable table for scanning by column, and a card grid with badges for browsing visually.",
    group: "Structured data",
    previewUrl: "/p/curata-internal/template-showcase-tables",
  },
  {
    slug: "showcase-tabs-accordion",
    title: "Tabs and Accordions",
    description: "Tabs for content that genuinely forks, and an accordion for optional detail someone can skip.",
    group: "Emphasis and layout",
    previewUrl: "/p/curata-internal/template-showcase-tabs-accordion",
  },
  {
    slug: "showcase-callouts",
    title: "Callouts, Badges, Dividers",
    description: "Every callout variant, every badge color, and labeled dividers, in a security-posture brief.",
    group: "Emphasis and layout",
    previewUrl: "/p/curata-internal/template-showcase-callouts",
  },
  {
    slug: "showcase-document",
    title: "Document: Print-Ready",
    description: "The document shell with print_flow set, built for a memo someone will export or print.",
    group: "Documents",
    previewUrl: "/p/curata-internal/template-showcase-document",
  },
  {
    slug: "ai-tool-pack",
    title: "AI Tool Pack",
    description: "Rules and guardrails that install into CLAUDE.md, AGENTS.md, and .cursorrules with kazam install",
    group: "Agents",
    previewUrl: "/p/curata-internal/template-ai-tool-pack",
  },
  {
    slug: "agent-skills-workflows",
    title: "Agent Skills & Workflows",
    description: "What your agents do, how they're triggered, what they produce",
    group: "Agents",
    previewUrl: "/p/curata-internal/template-agent-skills-workflows",
  },
];

export const GROUPS: string[] = [
  "Data",
  "Structure",
  "Sequence",
  "Layout",
  "Present",
  "Reuse",
  "Procedures",
  "Structured data",
  "Emphasis and layout",
  "Documents",
  "Agents",
];
