import fs from "fs/promises";
import path from "path";
import readline from "readline";

const ENV_TEMPLATE = `# Curata self-hosted configuration
# Generated by: curata init

AUTH_MODE={AUTH_MODE}
DATABASE_URL={DATABASE_URL}
SITES_ROOT={SITES_ROOT}
`;

const DOCKER_COMPOSE = `services:
  app:
    image: ghcr.io/tdiderich/curata-app:latest
    ports:
      - "3000:3000"
    environment:
      - AUTH_MODE=\${AUTH_MODE:-none}
      - DATABASE_URL=\${DATABASE_URL:-postgresql://curata:curata@postgres:5432/curata}
      - SITES_ROOT=\${SITES_ROOT:-/data/sites}
    volumes:
      - sites_data:/data/sites
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: curata
      POSTGRES_PASSWORD: curata
      POSTGRES_DB: curata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U curata"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
  sites_data:
`;

function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, resolve));
}

export async function runInit(): Promise<void> {
  const isInteractive = process.stdin.isTTY;

  let authMode = "none";
  let databaseUrl = "postgresql://curata:curata@postgres:5432/curata";
  let sitesRoot = "/data/sites";

  if (isInteractive) {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

    try {
      const authModeInput = await prompt(
        rl,
        "AUTH_MODE [none/clerk] (default: none): "
      );
      if (authModeInput.trim()) authMode = authModeInput.trim();

      const dbInput = await prompt(
        rl,
        `DATABASE_URL (default: ${databaseUrl}): `
      );
      if (dbInput.trim()) databaseUrl = dbInput.trim();

      const sitesInput = await prompt(
        rl,
        `SITES_ROOT (default: ${sitesRoot}): `
      );
      if (sitesInput.trim()) sitesRoot = sitesInput.trim();
    } finally {
      rl.close();
    }
  }

  const envContent = ENV_TEMPLATE
    .replace("{AUTH_MODE}", authMode)
    .replace("{DATABASE_URL}", databaseUrl)
    .replace("{SITES_ROOT}", sitesRoot);

  const envPath = path.join(process.cwd(), ".env");
  const composePath = path.join(process.cwd(), "docker-compose.yml");

  // Check for existing files
  const envExists = await fs.access(envPath).then(() => true).catch(() => false);
  const composeExists = await fs.access(composePath).then(() => true).catch(() => false);

  if (envExists) {
    console.log(".env already exists — skipping (delete it to regenerate)");
  } else {
    await fs.writeFile(envPath, envContent, "utf8");
    console.log("Created .env");
  }

  if (composeExists) {
    console.log("docker-compose.yml already exists — skipping (delete it to regenerate)");
  } else {
    await fs.writeFile(composePath, DOCKER_COMPOSE, "utf8");
    console.log("Created docker-compose.yml");
  }

  console.log("\nNext steps:");
  console.log("  1. Review .env and update any values");
  console.log("  2. Run: curata up");
  console.log("  3. Run: curata api-key");
  console.log("  4. Open http://localhost:3000");
}
